# Generated by Django 5.0 on 2024-01-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tag_delete_article_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uri',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
